name: Merge next into master
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Describe the type of version bump needed. Specify minor,major(default is patch)'
        required: true
        default: 'patch'
jobs:
  bump_and_merge:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout next branch code'
        uses: 'actions/checkout@v3'
        with:
          ref: next
          fetch-depth: 0

      - name: 'cat package.json'
        run: cat ./package.json

      - name: Detect changes in next wrt master
        id: cdc
        uses: younited/detect-branch-changes-action@v0.1.3
        with:
          base_branch: master

      - name:  'Automated Version Bump'
        if: ${{ steps.cdc.outputs.changed }}
        id: version-bump
        uses:  'phips28/gh-action-bump-version@master'
        with:
          version-type: ${{ github.event.inputs.bump_type }}
          # minor-wording:  'add,Adds,new,feat,minor,Update'
          # major-wording:  'MAJOR,cut-major,BREAKING CHANGE,major'
          # commit-message: 'CI: bumps version to {{version}}'
          # patch-wording:  'patch,fixes'

      # - name: 'Output Step'
      #   env:
      #     NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
      #   run: echo $NEW_TAG

      - name: Merge next -> master
        if: ${{ steps.cdc.outputs.changed }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: next
          target_branch: master
          message: Merge next into master
          github_token: ${{ secrets.GITHUB_TOKEN }}
