name: Merge next into master
on: workflow_dispatch
jobs:
  bump_and_merge:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout next branch code'
        uses: 'actions/checkout@v3'
        with:
          ref: next

      - name: 'cat package.json'
        run: cat ./package.json

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          commit-message: 'CI: bumps version to {{version}}'

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: npm pkg get version | sed 's/"//g' >> $NEW_TAG

      - name: 'Output version of package'
        run: echo "new tag $NEW_TAG"

      - name: 'Check github event data'
        run: echo "${{ github.event }}"

      - name: Merge next -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: next
          target_branch: master
          message: Merge next into master
          github_token: ${{ secrets.GITHUB_TOKEN }}
