name: Merge next into master
on: workflow_dispatch
jobs:
  bump_and_merge:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout next branch code'
        uses: 'actions/checkout@v3'
        with:
          ref: next

      - name: 'cat package.json'
        run: cat ./package.json

      - name:  'Automated Version Bump'
        id: version-bump
        uses:  'phips28/gh-action-bump-version@master'
        with:
          minor-wording:  'add,Adds,new,feat,minor,Update'
          major-wording:  'MAJOR,cut-major,BREAKING CHANGE,major'
          commit-message: 'CI: bumps version to {{version}}'
          # patch-wording:  'patch,fixes'

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo $NEW_TAG

      - name: Merge next -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: next
          target_branch: master
          message: Merge next with tag "$NEW_TAG" into master
          github_token: ${{ secrets.GITHUB_TOKEN }}
