name: Merge next into master
on: workflow_dispatch
jobs:
  merge_branch:
    name: "Merge next to master"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master

      - name: Merge next -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: next
          target_branch: master
          github_token: ${{ github.MERGE_MASTER }}
