name: Print commit difference
on: workflow_dispatch
jobs:
  bump_and_merge:
    name: 'Check commit difference between next and master'
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit Difference Count Between Two Branches
        id: cdc
        uses: jessicalostinspace/commit-difference-action@v1.0.0
        with:
          base-branch: 'next'
          secondary-branch: 'master'
      - name: Echo count
        run: |
          echo ${{ steps.cdc.outputs.commit-difference-count }}
